<?xml version="1.0" encoding="utf-8"?><Database Name="TTCSDL" Class="TTCSDLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DELL-PC\THANGMMT;Initial Catalog=TTCSDL;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="TTCSDLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TKUser" Member="TKUsers">
    <Type Name="TKUser">
      <Column Name="Ma" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TKUser_GroupUser" Member="GroupUsers" ThisKey="Ma" OtherKey="Ma" Type="GroupUser" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDV" Member="ChiTietDVs">
    <Type Name="ChiTietDV">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuongDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="DichVu_ChiTietDV" Member="DichVu" ThisKey="MaDV" OtherKey="MaDV" Type="DichVu" IsForeignKey="true" />
      <Association Name="HDDichVu_ChiTietDV" Member="HDDichVu" ThisKey="MaHD" OtherKey="MaHD" Type="HDDichVu" IsForeignKey="true" />
      <Association Name="NhanVien_ChiTietDV" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="MaDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DichVu_ChiTietDV" Member="ChiTietDVs" ThisKey="MaDV" OtherKey="MaDV" Type="ChiTietDV" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietThuePhong" Member="ChiTietThuePhongs">
    <Type Name="ChiTietThuePhong">
      <Column Name="MaPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HDThuePhong_ChiTietThuePhong" Member="HDThuePhong" ThisKey="MaPhong" OtherKey="MaPhong" Type="HDThuePhong" IsForeignKey="true" />
      <Association Name="Phong_ChiTietThuePhong" Member="Phong" ThisKey="SoPhong" OtherKey="SoPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDDichVu" Member="HDDichVus">
    <Type Name="HDDichVu">
      <Column Name="MaHD" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayLapHD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HDDichVu_ChiTietDV" Member="ChiTietDVs" ThisKey="MaHD" OtherKey="MaHD" Type="ChiTietDV" />
      <Association Name="KhachHang_HDDichVu" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDThanhToan" Member="HDThanhToans">
    <Type Name="HDThanhToan">
      <Column Name="MaHDTT" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaKHTT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTienThanhToan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HDThuePhong_HDThanhToan" Member="HDThuePhong" ThisKey="MaPhong" OtherKey="MaPhong" Type="HDThuePhong" IsForeignKey="true" />
      <Association Name="KhachHang_HDThanhToan" Member="KhachHang" ThisKey="MaKHTT" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HDThanhToan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDThuePhong" Member="HDThuePhongs">
    <Type Name="HDThuePhong">
      <Column Name="MaPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKHThue" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayThue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="HDThuePhong_ChiTietThuePhong" Member="ChiTietThuePhongs" ThisKey="MaPhong" OtherKey="MaPhong" Type="ChiTietThuePhong" />
      <Association Name="HDThuePhong_HDThanhToan" Member="HDThanhToans" ThisKey="MaPhong" OtherKey="MaPhong" Type="HDThanhToan" />
      <Association Name="HDThuePhong_ThuePhong" Member="ThuePhongs" ThisKey="MaPhong" OtherKey="MaPhong" Type="ThuePhong" />
      <Association Name="KhachHang_HDThuePhong" Member="KhachHang" ThisKey="MaKHThue" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HDThuePhong" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoCMT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CapBac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_HDDichVu" Member="HDDichVus" ThisKey="MaKH" OtherKey="MaKH" Type="HDDichVu" />
      <Association Name="KhachHang_HDThanhToan" Member="HDThanhToans" ThisKey="MaKH" OtherKey="MaKHTT" Type="HDThanhToan" />
      <Association Name="KhachHang_HDThuePhong" Member="HDThuePhongs" ThisKey="MaKH" OtherKey="MaKHThue" Type="HDThuePhong" />
      <Association Name="KhachHang_ThuePhong" Member="ThuePhongs" ThisKey="MaKH" OtherKey="MaKH" Type="ThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoCMT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NhanVien_ChiTietDV" Member="ChiTietDVs" ThisKey="MaNV" OtherKey="MaNV" Type="ChiTietDV" />
      <Association Name="NhanVien_HDThanhToan" Member="HDThanhToans" ThisKey="MaNV" OtherKey="MaNV" Type="HDThanhToan" />
      <Association Name="NhanVien_HDThuePhong" Member="HDThuePhongs" ThisKey="MaNV" OtherKey="MaNV" Type="HDThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="SoPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrangPhong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Phong_ChiTietThuePhong" Member="ChiTietThuePhongs" ThisKey="SoPhong" OtherKey="SoPhong" Type="ChiTietThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.ThuePhong" Member="ThuePhongs">
    <Type Name="ThuePhong">
      <Column Name="MaPhong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KhachHang_ThuePhong" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="HDThuePhong_ThuePhong" Member="HDThuePhong" ThisKey="MaPhong" OtherKey="MaPhong" Type="HDThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupUser" Member="GroupUsers">
    <Type Name="GroupUser">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ma" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TimeEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TKUser_GroupUser" Member="TKUser" ThisKey="Ma" OtherKey="Ma" Type="TKUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.addDV" Method="addDV">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="price" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RemoveUser" Method="RemoveUser">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addkhachhang" Method="addkhachhang">
    <Parameter Name="makh" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="tenkh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gt" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="socmt" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="phone" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="capbac" Type="System.Int32" DbType="Int" />
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addPhong" Method="addPhong">
    <Parameter Name="so" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="tinhtrang" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="timeedited" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.adduser" Method="adduser">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="user" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="mail" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="phone" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="group" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delDV" Method="delDV">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editDV" Method="editDV">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="price" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editkhachhang" Method="editkhachhang">
    <Parameter Name="makh" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="tenkh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ns" Type="System.DateTime" DbType="Date" />
    <Parameter Name="gt" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="socmt" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="phone" Type="System.String" DbType="NChar(20)" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="capbac" Type="System.Int32" DbType="Int" />
    <Parameter Name="time" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editPhong" Method="editPhong">
    <Parameter Name="so" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="loai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="tinhtrang" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="timeedited" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editUser" Method="editUser">
    <Parameter Name="ma" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="username" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="phone" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="timeedit" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RemoveKhachHang" Method="RemoveKhachHang">
    <Parameter Name="makh" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.removePhong" Method="removePhong">
    <Parameter Name="so" Type="System.String" DbType="NChar(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>