#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TTCSDL")]
	public partial class TTCSDLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTKUser(TKUser instance);
    partial void UpdateTKUser(TKUser instance);
    partial void DeleteTKUser(TKUser instance);
    partial void InsertChiTietDV(ChiTietDV instance);
    partial void UpdateChiTietDV(ChiTietDV instance);
    partial void DeleteChiTietDV(ChiTietDV instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertChiTietThuePhong(ChiTietThuePhong instance);
    partial void UpdateChiTietThuePhong(ChiTietThuePhong instance);
    partial void DeleteChiTietThuePhong(ChiTietThuePhong instance);
    partial void InsertHDDichVu(HDDichVu instance);
    partial void UpdateHDDichVu(HDDichVu instance);
    partial void DeleteHDDichVu(HDDichVu instance);
    partial void InsertHDThanhToan(HDThanhToan instance);
    partial void UpdateHDThanhToan(HDThanhToan instance);
    partial void DeleteHDThanhToan(HDThanhToan instance);
    partial void InsertHDThuePhong(HDThuePhong instance);
    partial void UpdateHDThuePhong(HDThuePhong instance);
    partial void DeleteHDThuePhong(HDThuePhong instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertThuePhong(ThuePhong instance);
    partial void UpdateThuePhong(ThuePhong instance);
    partial void DeleteThuePhong(ThuePhong instance);
    partial void InsertGroupUser(GroupUser instance);
    partial void UpdateGroupUser(GroupUser instance);
    partial void DeleteGroupUser(GroupUser instance);
    #endregion
		
		public TTCSDLDataContext() : 
				base(global::DAL.Properties.Settings.Default.TTCSDLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TTCSDLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTCSDLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTCSDLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TTCSDLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TKUser> TKUsers
		{
			get
			{
				return this.GetTable<TKUser>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDV> ChiTietDVs
		{
			get
			{
				return this.GetTable<ChiTietDV>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this.GetTable<ChiTietThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<HDDichVu> HDDichVus
		{
			get
			{
				return this.GetTable<HDDichVu>();
			}
		}
		
		public System.Data.Linq.Table<HDThanhToan> HDThanhToans
		{
			get
			{
				return this.GetTable<HDThanhToan>();
			}
		}
		
		public System.Data.Linq.Table<HDThuePhong> HDThuePhongs
		{
			get
			{
				return this.GetTable<HDThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<ThuePhong> ThuePhongs
		{
			get
			{
				return this.GetTable<ThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<GroupUser> GroupUsers
		{
			get
			{
				return this.GetTable<GroupUser>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addDV")]
		public int addDV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, name, price, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveUser")]
		public int RemoveUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addkhachhang")]
		public int addkhachhang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ns, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string socmt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tenkh, ns, gt, socmt, phone, diachi, capbac, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addPhong")]
		public int addPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string so, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string loai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> tinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeedited)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), so, loai, gia, tinhtrang, timeedited);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.adduser")]
		public int adduser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string mail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> group)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, user, pass, name, mail, phone, time, group);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delDV")]
		public int delDV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editDV")]
		public int editDV([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, name, price, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editkhachhang")]
		public int editkhachhang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ns, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string socmt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> time)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tenkh, ns, gt, socmt, phone, diachi, capbac, time);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editPhong")]
		public int editPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string so, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string loai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> tinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeedited)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), so, loai, gia, tinhtrang, timeedited);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editUser")]
		public int editUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> timeedit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, username, pass, name, email, phone, timeedit);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveKhachHang")]
		public int RemoveKhachHang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string makh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.removePhong")]
		public int removePhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string so)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), so);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TKUser")]
	public partial class TKUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma;
		
		private string _Username;
		
		private string _Pass;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _Phone;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntitySet<GroupUser> _GroupUsers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChanging(string value);
    partial void OnMaChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public TKUser()
		{
			this._GroupUsers = new EntitySet<GroupUser>(new Action<GroupUser>(this.attach_GroupUsers), new Action<GroupUser>(this.detach_GroupUsers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					this.OnMaChanging(value);
					this.SendPropertyChanging();
					this._Ma = value;
					this.SendPropertyChanged("Ma");
					this.OnMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(MAX)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TKUser_GroupUser", Storage="_GroupUsers", ThisKey="Ma", OtherKey="Ma")]
		public EntitySet<GroupUser> GroupUsers
		{
			get
			{
				return this._GroupUsers;
			}
			set
			{
				this._GroupUsers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GroupUsers(GroupUser entity)
		{
			this.SendPropertyChanging();
			entity.TKUser = this;
		}
		
		private void detach_GroupUsers(GroupUser entity)
		{
			this.SendPropertyChanging();
			entity.TKUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDV")]
	public partial class ChiTietDV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaDV;
		
		private System.Nullable<int> _SoLuongDV;
		
		private System.Nullable<int> _ThanhTien;
		
		private string _MaNV;
		
		private EntityRef<DichVu> _DichVu;
		
		private EntityRef<HDDichVu> _HDDichVu;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnSoLuongDVChanging(System.Nullable<int> value);
    partial void OnSoLuongDVChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public ChiTietDV()
		{
			this._DichVu = default(EntityRef<DichVu>);
			this._HDDichVu = default(EntityRef<HDDichVu>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._HDDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDV", DbType="Int")]
		public System.Nullable<int> SoLuongDV
		{
			get
			{
				return this._SoLuongDV;
			}
			set
			{
				if ((this._SoLuongDV != value))
				{
					this.OnSoLuongDVChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDV = value;
					this.SendPropertyChanged("SoLuongDV");
					this.OnSoLuongDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_ChiTietDV", Storage="_DichVu", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.ChiTietDVs.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.ChiTietDVs.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDDichVu_ChiTietDV", Storage="_HDDichVu", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public HDDichVu HDDichVu
		{
			get
			{
				return this._HDDichVu.Entity;
			}
			set
			{
				HDDichVu previousValue = this._HDDichVu.Entity;
				if (((previousValue != value) 
							|| (this._HDDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDDichVu.Entity = null;
						previousValue.ChiTietDVs.Remove(this);
					}
					this._HDDichVu.Entity = value;
					if ((value != null))
					{
						value.ChiTietDVs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("HDDichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietDV", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChiTietDVs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietDVs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<int> _GiaDV;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntitySet<ChiTietDV> _ChiTietDVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnGiaDVChanging(System.Nullable<int> value);
    partial void OnGiaDVChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public DichVu()
		{
			this._ChiTietDVs = new EntitySet<ChiTietDV>(new Action<ChiTietDV>(this.attach_ChiTietDVs), new Action<ChiTietDV>(this.detach_ChiTietDVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaDV", DbType="Int")]
		public System.Nullable<int> GiaDV
		{
			get
			{
				return this._GiaDV;
			}
			set
			{
				if ((this._GiaDV != value))
				{
					this.OnGiaDVChanging(value);
					this.SendPropertyChanging();
					this._GiaDV = value;
					this.SendPropertyChanged("GiaDV");
					this.OnGiaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_ChiTietDV", Storage="_ChiTietDVs", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<ChiTietDV> ChiTietDVs
		{
			get
			{
				return this._ChiTietDVs;
			}
			set
			{
				this._ChiTietDVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietThuePhong")]
	public partial class ChiTietThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _SoPhong;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntityRef<HDThuePhong> _HDThuePhong;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnSoPhongChanging(string value);
    partial void OnSoPhongChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public ChiTietThuePhong()
		{
			this._HDThuePhong = default(EntityRef<HDThuePhong>);
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._HDThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoPhongChanging(value);
					this.SendPropertyChanging();
					this._SoPhong = value;
					this.SendPropertyChanged("SoPhong");
					this.OnSoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_ChiTietThuePhong", Storage="_HDThuePhong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public HDThuePhong HDThuePhong
		{
			get
			{
				return this._HDThuePhong.Entity;
			}
			set
			{
				HDThuePhong previousValue = this._HDThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._HDThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDThuePhong.Entity = null;
						previousValue.ChiTietThuePhongs.Remove(this);
					}
					this._HDThuePhong.Entity = value;
					if ((value != null))
					{
						value.ChiTietThuePhongs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("HDThuePhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiTietThuePhong", Storage="_Phong", ThisKey="SoPhong", OtherKey="SoPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.ChiTietThuePhongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.ChiTietThuePhongs.Add(this);
						this._SoPhong = value.SoPhong;
					}
					else
					{
						this._SoPhong = default(string);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDDichVu")]
	public partial class HDDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayLapHD;
		
		private System.Nullable<int> _TongTien;
		
		private EntitySet<ChiTietDV> _ChiTietDVs;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayLapHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapHDChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HDDichVu()
		{
			this._ChiTietDVs = new EntitySet<ChiTietDV>(new Action<ChiTietDV>(this.attach_ChiTietDVs), new Action<ChiTietDV>(this.detach_ChiTietDVs));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHD", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapHD
		{
			get
			{
				return this._NgayLapHD;
			}
			set
			{
				if ((this._NgayLapHD != value))
				{
					this.OnNgayLapHDChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHD = value;
					this.SendPropertyChanged("NgayLapHD");
					this.OnNgayLapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDDichVu_ChiTietDV", Storage="_ChiTietDVs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<ChiTietDV> ChiTietDVs
		{
			get
			{
				return this._ChiTietDVs;
			}
			set
			{
				this._ChiTietDVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDDichVu", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HDDichVus.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HDDichVus.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.HDDichVu = this;
		}
		
		private void detach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.HDDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDThanhToan")]
	public partial class HDThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDTT;
		
		private string _MaPhong;
		
		private string _MaKHTT;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private System.Nullable<int> _TongTienThanhToan;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private string _MaNV;
		
		private System.Nullable<int> _GiamGia;
		
		private EntityRef<HDThuePhong> _HDThuePhong;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDTTChanging(string value);
    partial void OnMaHDTTChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnMaKHTTChanging(string value);
    partial void OnMaKHTTChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    partial void OnTongTienThanhToanChanging(System.Nullable<int> value);
    partial void OnTongTienThanhToanChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    #endregion
		
		public HDThanhToan()
		{
			this._HDThuePhong = default(EntityRef<HDThuePhong>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDTT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDTT
		{
			get
			{
				return this._MaHDTT;
			}
			set
			{
				if ((this._MaHDTT != value))
				{
					this.OnMaHDTTChanging(value);
					this.SendPropertyChanging();
					this._MaHDTT = value;
					this.SendPropertyChanged("MaHDTT");
					this.OnMaHDTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10)")]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._HDThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKHTT", DbType="NChar(10)")]
		public string MaKHTT
		{
			get
			{
				return this._MaKHTT;
			}
			set
			{
				if ((this._MaKHTT != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHTTChanging(value);
					this.SendPropertyChanging();
					this._MaKHTT = value;
					this.SendPropertyChanged("MaKHTT");
					this.OnMaKHTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienThanhToan", DbType="Int")]
		public System.Nullable<int> TongTienThanhToan
		{
			get
			{
				return this._TongTienThanhToan;
			}
			set
			{
				if ((this._TongTienThanhToan != value))
				{
					this.OnTongTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TongTienThanhToan = value;
					this.SendPropertyChanged("TongTienThanhToan");
					this.OnTongTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
		public System.Nullable<int> GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_HDThanhToan", Storage="_HDThuePhong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public HDThuePhong HDThuePhong
		{
			get
			{
				return this._HDThuePhong.Entity;
			}
			set
			{
				HDThuePhong previousValue = this._HDThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._HDThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDThuePhong.Entity = null;
						previousValue.HDThanhToans.Remove(this);
					}
					this._HDThuePhong.Entity = value;
					if ((value != null))
					{
						value.HDThanhToans.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("HDThuePhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDThanhToan", Storage="_KhachHang", ThisKey="MaKHTT", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HDThanhToans.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HDThanhToans.Add(this);
						this._MaKHTT = value.MaKH;
					}
					else
					{
						this._MaKHTT = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HDThanhToan", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HDThanhToans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HDThanhToans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HDThuePhong")]
	public partial class HDThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _MaKHThue;
		
		private System.Nullable<System.DateTime> _NgayThue;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private System.Nullable<int> _ThoiGianThue;
		
		private System.Nullable<int> _TienPhong;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private string _MaNV;
		
		private EntitySet<ChiTietThuePhong> _ChiTietThuePhongs;
		
		private EntitySet<HDThanhToan> _HDThanhToans;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnMaKHThueChanging(string value);
    partial void OnMaKHThueChanged();
    partial void OnNgayThueChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThueChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnThoiGianThueChanging(System.Nullable<int> value);
    partial void OnThoiGianThueChanged();
    partial void OnTienPhongChanging(System.Nullable<int> value);
    partial void OnTienPhongChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HDThuePhong()
		{
			this._ChiTietThuePhongs = new EntitySet<ChiTietThuePhong>(new Action<ChiTietThuePhong>(this.attach_ChiTietThuePhongs), new Action<ChiTietThuePhong>(this.detach_ChiTietThuePhongs));
			this._HDThanhToans = new EntitySet<HDThanhToan>(new Action<HDThanhToan>(this.attach_HDThanhToans), new Action<HDThanhToan>(this.detach_HDThanhToans));
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKHThue", DbType="NChar(10)")]
		public string MaKHThue
		{
			get
			{
				return this._MaKHThue;
			}
			set
			{
				if ((this._MaKHThue != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHThueChanging(value);
					this.SendPropertyChanging();
					this._MaKHThue = value;
					this.SendPropertyChanged("MaKHThue");
					this.OnMaKHThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThue", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThue
		{
			get
			{
				return this._NgayThue;
			}
			set
			{
				if ((this._NgayThue != value))
				{
					this.OnNgayThueChanging(value);
					this.SendPropertyChanging();
					this._NgayThue = value;
					this.SendPropertyChanged("NgayThue");
					this.OnNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianThue", DbType="Int")]
		public System.Nullable<int> ThoiGianThue
		{
			get
			{
				return this._ThoiGianThue;
			}
			set
			{
				if ((this._ThoiGianThue != value))
				{
					this.OnThoiGianThueChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianThue = value;
					this.SendPropertyChanged("ThoiGianThue");
					this.OnThoiGianThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhong", DbType="Int")]
		public System.Nullable<int> TienPhong
		{
			get
			{
				return this._TienPhong;
			}
			set
			{
				if ((this._TienPhong != value))
				{
					this.OnTienPhongChanging(value);
					this.SendPropertyChanging();
					this._TienPhong = value;
					this.SendPropertyChanged("TienPhong");
					this.OnTienPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_ChiTietThuePhong", Storage="_ChiTietThuePhongs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this._ChiTietThuePhongs;
			}
			set
			{
				this._ChiTietThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_HDThanhToan", Storage="_HDThanhToans", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<HDThanhToan> HDThanhToans
		{
			get
			{
				return this._HDThanhToans;
			}
			set
			{
				this._HDThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_ThuePhong", Storage="_ThuePhongs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDThuePhong", Storage="_KhachHang", ThisKey="MaKHThue", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HDThuePhongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HDThuePhongs.Add(this);
						this._MaKHThue = value.MaKH;
					}
					else
					{
						this._MaKHThue = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HDThuePhong", Storage="_NhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HDThuePhongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HDThuePhongs.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = this;
		}
		
		private void detach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = null;
		}
		
		private void attach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = this;
		}
		
		private void detach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = null;
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HDThuePhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _Gioitinh;
		
		private string _SoCMT;
		
		private string _SoDT;
		
		private string _DiaChi;
		
		private System.Nullable<int> _CapBac;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntitySet<HDDichVu> _HDDichVus;
		
		private EntitySet<HDThanhToan> _HDThanhToans;
		
		private EntitySet<HDThuePhong> _HDThuePhongs;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnSoCMTChanging(string value);
    partial void OnSoCMTChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnCapBacChanging(System.Nullable<int> value);
    partial void OnCapBacChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public KhachHang()
		{
			this._HDDichVus = new EntitySet<HDDichVu>(new Action<HDDichVu>(this.attach_HDDichVus), new Action<HDDichVu>(this.detach_HDDichVus));
			this._HDThanhToans = new EntitySet<HDThanhToan>(new Action<HDThanhToan>(this.attach_HDThanhToans), new Action<HDThanhToan>(this.detach_HDThanhToans));
			this._HDThuePhongs = new EntitySet<HDThuePhong>(new Action<HDThuePhong>(this.attach_HDThuePhongs), new Action<HDThuePhong>(this.detach_HDThuePhongs));
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMT", DbType="NChar(20)")]
		public string SoCMT
		{
			get
			{
				return this._SoCMT;
			}
			set
			{
				if ((this._SoCMT != value))
				{
					this.OnSoCMTChanging(value);
					this.SendPropertyChanging();
					this._SoCMT = value;
					this.SendPropertyChanged("SoCMT");
					this.OnSoCMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(20)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBac", DbType="Int")]
		public System.Nullable<int> CapBac
		{
			get
			{
				return this._CapBac;
			}
			set
			{
				if ((this._CapBac != value))
				{
					this.OnCapBacChanging(value);
					this.SendPropertyChanging();
					this._CapBac = value;
					this.SendPropertyChanged("CapBac");
					this.OnCapBacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDDichVu", Storage="_HDDichVus", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HDDichVu> HDDichVus
		{
			get
			{
				return this._HDDichVus;
			}
			set
			{
				this._HDDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDThanhToan", Storage="_HDThanhToans", ThisKey="MaKH", OtherKey="MaKHTT")]
		public EntitySet<HDThanhToan> HDThanhToans
		{
			get
			{
				return this._HDThanhToans;
			}
			set
			{
				this._HDThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HDThuePhong", Storage="_HDThuePhongs", ThisKey="MaKH", OtherKey="MaKHThue")]
		public EntitySet<HDThuePhong> HDThuePhongs
		{
			get
			{
				return this._HDThuePhongs;
			}
			set
			{
				this._HDThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ThuePhong", Storage="_ThuePhongs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HDDichVus(HDDichVu entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HDDichVus(HDDichVu entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HDThuePhongs(HDThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HDThuePhongs(HDThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _Gioitinh;
		
		private string _SoCMT;
		
		private string _SoDT;
		
		private string _QueQuan;
		
		private string _ChucVu;
		
		private System.Nullable<int> _Luong;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntitySet<ChiTietDV> _ChiTietDVs;
		
		private EntitySet<HDThanhToan> _HDThanhToans;
		
		private EntitySet<HDThuePhong> _HDThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnSoCMTChanging(string value);
    partial void OnSoCMTChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnLuongChanging(System.Nullable<int> value);
    partial void OnLuongChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChiTietDVs = new EntitySet<ChiTietDV>(new Action<ChiTietDV>(this.attach_ChiTietDVs), new Action<ChiTietDV>(this.detach_ChiTietDVs));
			this._HDThanhToans = new EntitySet<HDThanhToan>(new Action<HDThanhToan>(this.attach_HDThanhToans), new Action<HDThanhToan>(this.detach_HDThanhToans));
			this._HDThuePhongs = new EntitySet<HDThuePhong>(new Action<HDThuePhong>(this.attach_HDThuePhongs), new Action<HDThuePhong>(this.detach_HDThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMT", DbType="NChar(20)")]
		public string SoCMT
		{
			get
			{
				return this._SoCMT;
			}
			set
			{
				if ((this._SoCMT != value))
				{
					this.OnSoCMTChanging(value);
					this.SendPropertyChanging();
					this._SoCMT = value;
					this.SendPropertyChanged("SoCMT");
					this.OnSoCMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NChar(20)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(50)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="Int")]
		public System.Nullable<int> Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietDV", Storage="_ChiTietDVs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<ChiTietDV> ChiTietDVs
		{
			get
			{
				return this._ChiTietDVs;
			}
			set
			{
				this._ChiTietDVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HDThanhToan", Storage="_HDThanhToans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HDThanhToan> HDThanhToans
		{
			get
			{
				return this._HDThanhToans;
			}
			set
			{
				this._HDThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HDThuePhong", Storage="_HDThuePhongs", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HDThuePhong> HDThuePhongs
		{
			get
			{
				return this._HDThuePhongs;
			}
			set
			{
				this._HDThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChiTietDVs(ChiTietDV entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HDThanhToans(HDThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HDThuePhongs(HDThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HDThuePhongs(HDThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhong;
		
		private string _LoaiPhong;
		
		private System.Nullable<int> _GiaPhong;
		
		private System.Nullable<bool> _TinhTrangPhong;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntitySet<ChiTietThuePhong> _ChiTietThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhongChanging(string value);
    partial void OnSoPhongChanged();
    partial void OnLoaiPhongChanging(string value);
    partial void OnLoaiPhongChanged();
    partial void OnGiaPhongChanging(System.Nullable<int> value);
    partial void OnGiaPhongChanged();
    partial void OnTinhTrangPhongChanging(System.Nullable<bool> value);
    partial void OnTinhTrangPhongChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public Phong()
		{
			this._ChiTietThuePhongs = new EntitySet<ChiTietThuePhong>(new Action<ChiTietThuePhong>(this.attach_ChiTietThuePhongs), new Action<ChiTietThuePhong>(this.detach_ChiTietThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhong
		{
			get
			{
				return this._SoPhong;
			}
			set
			{
				if ((this._SoPhong != value))
				{
					this.OnSoPhongChanging(value);
					this.SendPropertyChanging();
					this._SoPhong = value;
					this.SendPropertyChanged("SoPhong");
					this.OnSoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiPhong", DbType="NVarChar(50)")]
		public string LoaiPhong
		{
			get
			{
				return this._LoaiPhong;
			}
			set
			{
				if ((this._LoaiPhong != value))
				{
					this.OnLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._LoaiPhong = value;
					this.SendPropertyChanged("LoaiPhong");
					this.OnLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaPhong", DbType="Int")]
		public System.Nullable<int> GiaPhong
		{
			get
			{
				return this._GiaPhong;
			}
			set
			{
				if ((this._GiaPhong != value))
				{
					this.OnGiaPhongChanging(value);
					this.SendPropertyChanging();
					this._GiaPhong = value;
					this.SendPropertyChanged("GiaPhong");
					this.OnGiaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangPhong", DbType="Bit")]
		public System.Nullable<bool> TinhTrangPhong
		{
			get
			{
				return this._TinhTrangPhong;
			}
			set
			{
				if ((this._TinhTrangPhong != value))
				{
					this.OnTinhTrangPhongChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangPhong = value;
					this.SendPropertyChanged("TinhTrangPhong");
					this.OnTinhTrangPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiTietThuePhong", Storage="_ChiTietThuePhongs", ThisKey="SoPhong", OtherKey="SoPhong")]
		public EntitySet<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this._ChiTietThuePhongs;
			}
			set
			{
				this._ChiTietThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuePhong")]
	public partial class ThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _MaKH;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<HDThuePhong> _HDThuePhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public ThuePhong()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._HDThuePhong = default(EntityRef<HDThuePhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._HDThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ThuePhong", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HDThuePhong_ThuePhong", Storage="_HDThuePhong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public HDThuePhong HDThuePhong
		{
			get
			{
				return this._HDThuePhong.Entity;
			}
			set
			{
				HDThuePhong previousValue = this._HDThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._HDThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HDThuePhong.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._HDThuePhong.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("HDThuePhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GroupUser")]
	public partial class GroupUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _Nhom;
		
		private string _Ma;
		
		private System.Nullable<System.DateTime> _TimeEdited;
		
		private EntityRef<TKUser> _TKUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNhomChanging(System.Nullable<int> value);
    partial void OnNhomChanged();
    partial void OnMaChanging(string value);
    partial void OnMaChanged();
    partial void OnTimeEditedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeEditedChanged();
    #endregion
		
		public GroupUser()
		{
			this._TKUser = default(EntityRef<TKUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="Int")]
		public System.Nullable<int> Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this.OnNhomChanging(value);
					this.SendPropertyChanging();
					this._Nhom = value;
					this.SendPropertyChanged("Nhom");
					this.OnNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma", DbType="NChar(10)")]
		public string Ma
		{
			get
			{
				return this._Ma;
			}
			set
			{
				if ((this._Ma != value))
				{
					if (this._TKUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChanging(value);
					this.SendPropertyChanging();
					this._Ma = value;
					this.SendPropertyChanged("Ma");
					this.OnMaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeEdited", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeEdited
		{
			get
			{
				return this._TimeEdited;
			}
			set
			{
				if ((this._TimeEdited != value))
				{
					this.OnTimeEditedChanging(value);
					this.SendPropertyChanging();
					this._TimeEdited = value;
					this.SendPropertyChanged("TimeEdited");
					this.OnTimeEditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TKUser_GroupUser", Storage="_TKUser", ThisKey="Ma", OtherKey="Ma", IsForeignKey=true)]
		public TKUser TKUser
		{
			get
			{
				return this._TKUser.Entity;
			}
			set
			{
				TKUser previousValue = this._TKUser.Entity;
				if (((previousValue != value) 
							|| (this._TKUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TKUser.Entity = null;
						previousValue.GroupUsers.Remove(this);
					}
					this._TKUser.Entity = value;
					if ((value != null))
					{
						value.GroupUsers.Add(this);
						this._Ma = value.Ma;
					}
					else
					{
						this._Ma = default(string);
					}
					this.SendPropertyChanged("TKUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
